title: Afaik IT
description: As far as ...
remote_theme: just-the-docs

url: https://afaik.it

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_enabled: true